openapi: 3.0.1
info:
  title: POSSE API
  version: 1.0.0
servers:
- url: https://bkrs3waxwg.execute-api.ap-northeast-1.amazonaws.com/default
paths:
  /news:
    get:
      summary: News一覧を取得します
      responses:
        200:
          description: successful operation
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/News'
        400:
          description: Invalid status value
          content: {}
  /news/{id}:
    get:
      summary: 指定したIDのNewsを取得します
      parameters:
      - name: id
        in: path
        description: news_id
        required: true
        schema:
          type: integer
      responses:
        200:
          description: successful operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/News'
        400:
          description: Invalid status value
          content: {}
components:
  schemas:
    News:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: 【講演会記事】26歳でエンジニアになったら人生変わった話
        text:
          type: string
          example: 「転職業界から見たエンジニア」「今の大学生に伝えたいこと」についてリクルートの遠竹様に語っていただきました！ここでは講演内容と、POSSE生が得た新たな知見についてご紹介します！
            あなたもこの記事でパラダイムシフトしませんか？
        thumbnail_url:
          type: string
          example: https://blog.posse-ap.com/wp-content/uploads/2021/11/Web%E3%83%A1%E3%83%87%E3%82%A3%E3%82%A2-%E3%80%8C-%E5%B0%B1%E6%B4%BB%E3%81%AE%E6%95%99%E7%A7%91%E6%9B%B8%E3%80%8D-%E3%81%AB%E5%8F%96%E6%9D%90%E3%81%95%E3%82%8C%E3%81%BE%E3%81%97%E3%81%9F-6.jpg
        date:
          type: string
          example: 2022-01-17
        author:
          $ref: '#/components/schemas/Author'
    Author:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 石井潤
        picture_url:
          type: string
          example: https://blog.posse-ap.com/wp-content/uploads/2021/11/ishii-1024x1021.jpeg
